-- ================================================
-- SQL Server Script generated by SSMS
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

USE [RealLingua]
GO

-- ------------------------------------------------
-- Table: Users
-- ------------------------------------------------

IF OBJECT_ID('[dbo].[USER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USER]
GO

CREATE TABLE [dbo].[USER] (
    [USER_ID] [int] NOT NULL IDENTITY(1,1),
    [NAME] [nvarchar](150) NOT NULL,
    [EMAIL] [nvarchar](250) NOT NULL,
    [PW_HASH] [nvarchar](400) NOT NULL,
    [DISCOUNT] [tinyint] NULL DEFAULT (0),
    [EMAIL_VERIFIED_FLAG] [nvarchar](1) NOT NULL DEFAULT ('N'),
    [CREATE_DATE] [datetime2](7) NOT NULL,
    [UPDATE_DATE] [datetime2](7) NULL,
    [VERIFICATION_HASH] [nvarchar](400) NULL,
    [RESET_HASH] [nvarchar](400) NULL,
    [FREE_TRIAL_COMPLETED] [nvarchar](1) NOT NULL DEFAULT ('N'),
    CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([USER_ID] ASC)
)
GO

-- ------------------------------------------------
-- Table: Language
-- ------------------------------------------------

CREATE TABLE [dbo].[LANGUAGE] (
    [LANGUAGE_ID] [int] NOT NULL IDENTITY(1,1),
    [LIVE] [nvarchar](1) NOT NULL DEFAULT ('N'),
    [NAME] [nvarchar](150) NOT NULL,
    [DESCRIPTION] [nvarchar](4000) NOT NULL,
    [ORIGIN] [nvarchar](1000) NOT NULL,
    [REGION] [nvarchar](1000) NOT NULL,
    [NUM_OF_SPEAKERS] [nvarchar](1000) NOT NULL,
    [THUMBNAIL_IMAGE_URL] [nvarchar](500) NULL,
    [HEADER_IMG_URL] [nvarchar](500) NULL,
    [CREATE_DATE] [datetime2](7) NOT NULL,
    [UPDATE_DATE] [datetime2](7) NULL,
    CONSTRAINT [PK_LANGUAGE] PRIMARY KEY CLUSTERED ([LANGUAGE_ID] ASC)
)
GO

-- ------------------------------------------------
-- Table: Language Level
-- ------------------------------------------------

CREATE TABLE [dbo].[LANGUAGE_LEVEL] (
    [LANGUAGE_LEVEL_ID] [int] NOT NULL IDENTITY(1,1),
    [LANGUAGE_ID] [int] NOT NULL,
    [NAME] [nvarchar](150) NOT NULL,
    [DESCRIPTION] [nvarchar](4000) NOT NULL,
    [TITLE] [nvarchar](150) NULL,
    [GO_TEXT] [nvarchar](50) NULL,
    [PRICE] [int] NOT NULL,
    [START_PAGE_TEXT] [nvarchar](4000) NOT NULL,
    [FINISH_PAGE_TEXT] [nvarchar](4000) NOT NULL,
    [ACTIVE] [nvarchar](1) NOT NULL DEFAULT ('Y'),
    [CREATE_DATE] [datetime2](7) NOT NULL,
    [UPDATE_DATE] [datetime2](7) NULL,
    [ENCOURAGEMENT] [nvarchar](200) NULL,
    CONSTRAINT [PK_LANGUAGE_LEVEL] PRIMARY KEY CLUSTERED ([LANGUAGE_LEVEL_ID] ASC),
    CONSTRAINT [FK_LANGUAGE_LEVEL_LANGUAGE] FOREIGN KEY ([LANGUAGE_ID]) REFERENCES [dbo].[LANGUAGE]([LANGUAGE_ID])
)
GO

-- ------------------------------------------------
-- Table: Video Content
-- ------------------------------------------------

CREATE TABLE [dbo].[VIDEO_CONTENT] (
    [VIDEO_CONTENT_ID] [int] NOT NULL IDENTITY(1,1),
    [TITLE] [nvarchar](500) NOT NULL,
    [MEDIA_URL] [nvarchar](4000) NOT NULL,
    [VALUE] [nvarchar](4000) NOT NULL,
    [CREATE_DATE] [datetime2](7) NOT NULL,
    [UPDATE_DATE] [datetime2](7) NULL,
    CONSTRAINT [PK_VIDEO_CONTENT] PRIMARY KEY CLUSTERED ([VIDEO_CONTENT_ID] ASC)
)
GO

-- ------------------------------------------------
-- Table: Module
-- ------------------------------------------------

CREATE TABLE [dbo].[MODULE] (
    [MODULE_ID] [int] NOT NULL IDENTITY(1,1),
    [LANGUAGE_LEVEL_ID] [int] NOT NULL,
    [VIDEO_CONTENT_ID] [int] NOT NULL,
    [NAME] [nvarchar](500) NULL,
    [DESCRIPTION] [nvarchar](4000) NOT NULL,
    [MODULE_FLOW_INDEX] [int] NOT NULL,
    [ACTIVE] [nvarchar](1) NOT NULL DEFAULT ('Y'),
    [CREATE_DATE] [datetime2](7) NOT NULL,
    [UPDATE_DATE] [datetime2](7) NULL,
    CONSTRAINT [PK_MODULE] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC),
    CONSTRAINT [FK_MODULE_LANGUAGE_LEVEL] FOREIGN KEY ([LANGUAGE_LEVEL_ID]) REFERENCES [dbo].[LANGUAGE_LEVEL]([LANGUAGE_LEVEL_ID]),
    CONSTRAINT [FK_MODULE_VIDEO_CONTENT] FOREIGN KEY ([VIDEO_CONTENT_ID]) REFERENCES [dbo].[VIDEO_CONTENT]([VIDEO_CONTENT_ID])
)
GO

-- ------------------------------------------------
-- Table: Activity
-- ------------------------------------------------

CREATE TABLE [dbo].[ACTIVITY] (
    [ACTIVITY_ID] [int] NOT NULL IDENTITY(1,1),
    [MODULE_ID] [int] NOT NULL,
    [ACTIVITY_TABLE] [nvarchar](150) NOT NULL,
    [NAME] [nvarchar](150) NOT NULL,
    [DESCRIPTION] [nvarchar](max) NOT NULL,
    [ACTIVE] [nvarchar](1) NOT NULL DEFAULT ('Y'),
    [CREATE_DATE] [datetime2](7) NOT NULL,
    [UPDATE_DATE] [datetime2](7) NULL,
    CONSTRAINT [PK_ACTIVITY] PRIMARY KEY CLUSTERED ([ACTIVITY_ID] ASC),
    CONSTRAINT [FK_ACTIVITY_MODULE] FOREIGN KEY ([MODULE_ID]) REFERENCES [dbo].[MODULE]([MODULE_ID]) ON DELETE CASCADE
)
GO

-- ------------------------------------------------
-- Table: Settings
-- ------------------------------------------------

CREATE TABLE [dbo].[SETTINGS] (
    [SETTINGS_ID] [int] NOT NULL IDENTITY(1,1),
    [KEY] [nvarchar](50) NOT NULL,
    [VALUE] [nvarchar](4000) NOT NULL,
    [CREATE_DATE] [datetime2](7) NOT NULL,
    [UPDATE_DATE] [datetime2](7) NULL,
    CONSTRAINT [PK_SETTINGS] PRIMARY KEY CLUSTERED ([SETTINGS_ID] ASC)
)
GO

-- ------------------------------------------------
-- Table: Word Bank
-- ------------------------------------------------

CREATE TABLE [dbo].[WORD_BANK] (
    [WORD_BANK_ID] [int] NOT NULL IDENTITY(1,1),
    [MODULE_ID] [int] NULL,
    [TARGET_WORD] [nvarchar](45) NULL,
    [WORKING_WORD] [nvarchar](45) NULL,
    CONSTRAINT [PK_WORD_BANK] PRIMARY KEY CLUSTERED ([WORD_BANK_ID] ASC),
    CONSTRAINT [FK_WORD_BANK_MODULE] FOREIGN KEY ([MODULE_ID]) REFERENCES [dbo].[MODULE]([MODULE_ID]) ON DELETE CASCADE
)
GO

-- ------------------------------------------------
-- Table: Type Test (covers MSSQL-specific types)
-- ------------------------------------------------

CREATE TABLE [dbo].[TYPE_TEST] (
    [ID] [bigint] NOT NULL IDENTITY(1,1),
    [LABEL] [varchar](255) NOT NULL,
    [UNICODE_LABEL] [nchar](100) NULL,
    [GUID] [uniqueidentifier] NOT NULL DEFAULT (NEWID()),
    [PRICE] [money] NULL,
    [SMALL_PRICE] [smallmoney] NULL,
    [SCORE] [float](53) NULL,
    [RATING] [real] NULL,
    [AMOUNT] [decimal](10,2) NULL,
    [IS_ACTIVE] [bit] NOT NULL DEFAULT (1),
    [BIRTH_DATE] [date] NULL,
    [LOGIN_TIME] [time](7) NULL,
    [CREATED_AT] [datetime] NOT NULL DEFAULT (GETDATE()),
    [MODIFIED_AT] [datetimeoffset](7) NULL,
    [SMALL_DT] [smalldatetime] NULL,
    [NOTES] [ntext] NULL,
    [PHOTO] [image] NULL,
    [DATA] [xml] NULL,
    CONSTRAINT [PK_TYPE_TEST] PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

-- ------------------------------------------------
-- Indexes
-- ------------------------------------------------

CREATE NONCLUSTERED INDEX [IX_ACTIVITY_MODULE_ID] ON [dbo].[ACTIVITY] ([MODULE_ID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_USER_EMAIL] ON [dbo].[USER] ([EMAIL] ASC)
GO
